-- Phase 9 verification checklist.
-- Run with `supabase test db` after applying migration 0009.
--
-- AI knowledge:
-- 1. knowledge_sources and knowledge_chunks have RLS enabled.
-- 2. anon/authenticated can read active knowledge only.
-- 3. search_pramuka_knowledge returns only active, source-backed chunks.
-- 4. staff can manage knowledge; public clients cannot write knowledge.
-- 5. Tunas abstains when a Pramuka question has no retrieval evidence.
--
-- QR attendance:
-- 6. create_attendance_session result does not contain token_hash or pin_hash.
-- 7. unauthenticated callers cannot execute create/check-in RPCs.
-- 8. inactive members cannot check in.
-- 9. five failed PIN attempts in a five-minute window are blocked.
-- 10. duplicate check-in is idempotent.
-- 11. max_checkins is enforced while the session row is locked.
-- 12. public QR lookup exposes metadata only, never hashes/PIN.
