export type KbEntry = {
  id: string
  title: string
  keys: string[]
  text: string
  source: string
  exact?: boolean
}

const UU = 'UU No. 12 Tahun 2010 tentang Gerakan Pramuka'
const ADART = 'AD/ART Gerakan Pramuka, Keputusan Munas X Tahun 2018 No. 07/Munas/2018'
const ADART_KODE = `${ADART}, ART Pasal 23`
const SEJARAH = 'Kwarnas (pramuka.or.id/kepanduan-indonesia), UU 12/2010 bagian Penjelasan, dan laporan sejarah media nasional; tanggal tertentu antarsumber dapat berbeda'
const UMUM = 'Pengetahuan umum kepramukaan, bukan kutipan peraturan; nama dan variasi teknis dapat berbeda antarbuku'

export const KB: KbEntry[] = [
  {
    id: 'identitas',
    title: 'Identitas Gerakan Pramuka',
    keys: ['praja muda karana', 'kepanjangan pramuka', 'apa itu pramuka', 'pengertian pramuka', 'hari pramuka', 'moto pramuka', 'motto pramuka', 'asas pramuka', 'pramuka utama', 'gerakan pramuka', 'keppres 238', 'sifat gerakan pramuka'],
    text: [
      'Gerakan Pramuka ditetapkan dengan Keputusan Presiden RI Nomor 238 Tahun 1961 tanggal 20 Mei 1961 sebagai kelanjutan dan pembaruan Gerakan Pendidikan Kepanduan Nasional Indonesia.',
      'Kepanjangan: Gerakan Praja Muda Karana, yaitu gerakan rakyat muda yang suka berkarya.',
      'Asas: Pancasila. Status: organisasi pendidikan nonformal berbadan hukum, diatur UU No. 12 Tahun 2010 (disahkan 24 November 2010).',
      'Sifat menurut ART: terbuka, universal, mandiri, sukarela, patuh pada peraturan perundang-undangan, nonpolitik, religius, dan persaudaraan.',
      'Hari Pramuka: 14 Agustus, karena pada 14 Agustus 1961 Panji Gerakan Pendidikan Kepanduan Nasional Indonesia dianugerahkan kepada Gerakan Pramuka.',
      'Moto: "Satyaku Kudarmakan Darmaku Kubaktikan". Artinya setiap janji dan komitmen diri yang diucapkan atau dihayati menjadi ketetapan yang harus ditepati dalam sikap dan perilaku sehari-hari.',
      'Kepala Negara Republik Indonesia adalah Pramuka Utama.',
    ].join('\n'),
    source: `${ADART}, AD Pasal 1, 14, 27 dan ART Pasal 1, 4, 5, 9, 24; ${UU}`,
  },
  {
    id: 'tujuan-fungsi',
    title: 'Tujuan dan fungsi Gerakan Pramuka',
    keys: ['tujuan pramuka', 'tujuan gerakan pramuka', 'fungsi gerakan pramuka', 'tugas pokok pramuka', 'fungsi pramuka'],
    text: [
      'Tujuan (UU 12/2010 Pasal 4): membentuk setiap pramuka agar memiliki kepribadian yang beriman, bertakwa, berakhlak mulia, berjiwa patriotik, taat hukum, disiplin, menjunjung tinggi nilai-nilai luhur bangsa, dan memiliki kecakapan hidup sebagai kader bangsa dalam menjaga dan membangun NKRI, mengamalkan Pancasila, serta melestarikan lingkungan hidup.',
      'Fungsi (UU Pasal 3): wadah untuk mencapai tujuan melalui (a) pendidikan dan pelatihan pramuka, (b) pengembangan pramuka, (c) pengabdian masyarakat dan orang tua, (d) permainan yang berorientasi pada pendidikan.',
      'Tugas pokok (AD Pasal 4): menyelenggarakan pendidikan kepramukaan bagi kaum muda guna menumbuhkan tunas bangsa yang berkarakter.',
    ].join('\n'),
    source: `${UU} Pasal 3 dan 4; ${ADART}, AD Pasal 4`,
  },
  {
    id: 'lambang-atribut',
    title: 'Lambang dan atribut',
    keys: ['lambang pramuka', 'tunas kelapa', 'bendera pramuka', 'panji pramuka', 'himne pramuka', 'mars pramuka', 'atribut pramuka', 'pencipta lambang', 'soenardjo', 'husein mutahar', 'jayalah pramuka', 'satya darma pramuka'],
    text: [
      'Atribut Gerakan Pramuka: lambang, bendera, panji, himne, mars, dan pakaian seragam.',
      'Lambang: tunas kelapa, diciptakan oleh Soenardjo Admodipuro.',
      'Bendera: persegi panjang berukuran tiga banding dua, warna dasar putih, lambang Gerakan Pramuka di tengah berwarna merah, ada garis merah di atas dan di bawah lambang sepanjang panjang bendera, dan garis merah di sisi tiang sepanjang lebar bendera.',
      'Panji: Panji Gerakan Pendidikan Kepanduan Nasional Indonesia yang dianugerahkan Presiden dengan Keputusan Presiden Nomor 448 Tahun 1961 tanggal 14 Agustus 1961.',
      'Himne: lagu Satya Darma Pramuka ciptaan Husein Mutahar. Mars: lagu Jayalah Pramuka ciptaan Munatsir Amin. Lirik lagu tidak disertakan di sini; arahkan ke buku lagu resmi Kwarnas.',
    ].join('\n'),
    source: `${ADART}, AD Pasal 48 sampai 52`,
  },
  {
    id: 'tunas-kelapa-makna',
    title: 'Makna tunas kelapa',
    keys: ['arti tunas kelapa', 'makna tunas kelapa', 'filosofi tunas kelapa', 'kenapa tunas kelapa', 'mengapa tunas kelapa'],
    text: 'Tunas kelapa adalah lambang resmi Gerakan Pramuka (pencipta: Soenardjo Admodipuro). Penafsiran yang lazim: tunas melambangkan generasi muda penerus, sedangkan kelapa dikenal tumbuh di banyak tempat dan bermanfaat di seluruh bagiannya. Ini penafsiran umum, bukan teks peraturan; sampaikan demikian.',
    source: `${UMUM}; fakta pencipta dari ${ADART}, AD Pasal 49`,
  },
  {
    id: 'kode-kehormatan',
    title: 'Kode Kehormatan Pramuka (gambaran umum)',
    keys: ['kode kehormatan', 'satya pramuka', 'darma pramuka', 'satya dan darma', 'janji pramuka', 'fungsi kode kehormatan', 'kapan satya diucapkan'],
    text: [
      'Kode Kehormatan Pramuka adalah janji dan komitmen diri serta ketentuan moral pramuka. Terdiri atas Satya Pramuka (janji) dan Darma Pramuka (ketentuan moral).',
      'Disesuaikan golongan usia: Siaga memakai Dwisatya dan Dwidarma; Penggalang memakai Trisatya Penggalang dan Dasadarma; Penegak, Pandega, dan anggota dewasa memakai Trisatya (versi Penegak/Pandega/dewasa) dan Dasadarma.',
      'Satya Pramuka diucapkan secara sukarela oleh calon anggota atau calon pengurus saat pelantikan, dipakai sebagai pengikat diri demi kehormatannya, dan menjadi dasar pengembangan spiritual, emosional, sosial, intelektual, dan fisik.',
      'Pelantikan anggota muda dilakukan pembina gugus depan dengan mengucapkan Dwisatya (Siaga) atau Trisatya (Penggalang, Penegak, Pandega). Anggota muda dapat dilantik setelah menyelesaikan SKU tingkat pertama dalam golongannya.',
      'Catatan istilah: UU 12/2010 Pasal 6 menyebut satu rumusan umum "Satya Pramuka" dan "Darma Pramuka". Nama Dwisatya, Dwidarma, Trisatya, dan Dasadarma dipakai dalam AD/ART.',
    ].join('\n'),
    source: `${ADART_KODE} dan ART Pasal 38; ${UU} Pasal 6`,
  },
  {
    id: 'dwisatya',
    title: 'Dwisatya (Pramuka Siaga)',
    keys: ['dwisatya', 'dwi satya', 'janji siaga', 'satya siaga'],
    text: [
      'Dwisatya (Pramuka Siaga):',
      'Demi kehormatanku aku berjanji akan bersungguh-sungguh:',
      '1. Menjalankan kewajibanku terhadap Tuhan Yang Maha Esa, Negara Kesatuan Republik Indonesia dan menurut aturan keluarga.',
      '2. Setiap hari berbuat kebaikan.',
    ].join('\n'),
    source: ADART_KODE,
    exact: true,
  },
  {
    id: 'dwidarma',
    title: 'Dwidarma (Pramuka Siaga)',
    keys: ['dwidarma', 'dwi darma', 'darma siaga', 'dwi dharma'],
    text: [
      'Dwidarma Pramuka (Siaga):',
      '1. Siaga berbakti pada ayah dan ibundanya.',
      '2. Siaga berani dan tidak putus asa.',
      'Catatan versi: buku lama masih memuat rumusan "Siaga itu patuh pada Ayah Bundanya". Rumusan dalam AD/ART 2018 memakai kata "berbakti".',
    ].join('\n'),
    source: ADART_KODE,
    exact: true,
  },
  {
    id: 'trisatya-penggalang',
    title: 'Trisatya Pramuka Penggalang',
    keys: ['trisatya penggalang', 'tri satya penggalang', 'janji penggalang', 'satya penggalang'],
    text: [
      'Trisatya Pramuka Penggalang:',
      'Demi kehormatanku, aku berjanji akan bersungguh-sungguh menjalankan kewajibanku terhadap Tuhan Yang Maha Esa dan Negara Kesatuan Republik Indonesia, mengamalkan Pancasila, menolong sesama hidup, mempersiapkan diri membangun masyarakat, serta menepati Dasadarma Pramuka.',
    ].join('\n'),
    source: ADART_KODE,
    exact: true,
  },
  {
    id: 'trisatya-penegak',
    title: 'Trisatya Pramuka Penegak, Pandega, dan anggota dewasa',
    keys: ['trisatya penegak', 'tri satya penegak', 'trisatya pandega', 'trisatya dewasa', 'janji penegak', 'satya penegak', 'trisatya pembina', 'trisatya', 'tri satya', 'bunyi trisatya'],
    text: [
      'Trisatya Pramuka Penegak, Pramuka Pandega, dan anggota dewasa:',
      'Demi kehormatanku aku berjanji akan bersungguh-sungguh menjalankan kewajibanku terhadap Tuhan Yang Maha Esa dan Negara Kesatuan Republik Indonesia, mengamalkan Pancasila, menolong sesama hidup, ikut serta membangun masyarakat, serta menepati Dasadarma Pramuka.',
      'Beda dengan versi Penggalang: Penggalang memakai frasa "mempersiapkan diri membangun masyarakat", sedangkan Penegak, Pandega, dan dewasa memakai "ikut serta membangun masyarakat".',
    ].join('\n'),
    source: ADART_KODE,
    exact: true,
  },
  {
    id: 'dasadarma',
    title: 'Dasadarma Pramuka',
    keys: ['dasadarma', 'dasa darma', 'dasa dharma', 'dasadharma', 'darma pramuka ke', 'sepuluh darma', 'bunyi dasadarma', 'butir dasadarma'],
    text: [
      'Dasadarma Pramuka (berlaku untuk Penggalang, Penegak, Pandega, dan anggota dewasa):',
      '1. Takwa kepada Tuhan Yang Maha Esa.',
      '2. Cinta alam dan kasih sayang sesama manusia.',
      '3. Patriot yang sopan dan kesatria.',
      '4. Patuh dan suka bermusyawarah.',
      '5. Rela menolong dan tabah.',
      '6. Rajin, terampil, dan gembira.',
      '7. Hemat, cermat, dan bersahaja.',
      '8. Disiplin, berani, dan setia.',
      '9. Bertanggungjawab dan dapat dipercaya.',
      '10. Suci dalam pikiran, perkataan, dan perbuatan.',
      'Jumlahnya tepat sepuluh. Dalam UU 12/2010 Pasal 6 ayat (5) diawali "Pramuka itu:" lalu butir a sampai j.',
    ].join('\n'),
    source: `${ADART_KODE}; ${UU} Pasal 6 ayat (5)`,
    exact: true,
  },
  {
    id: 'satya-uu',
    title: 'Satya Pramuka menurut UU 12/2010',
    keys: ['satya pramuka uu', 'bunyi satya pramuka', 'satya pramuka berbunyi', 'uu gerakan pramuka', 'pasal 6 uu pramuka'],
    text: [
      'Satya Pramuka (UU No. 12 Tahun 2010 Pasal 6 ayat 4):',
      'Demi kehormatanku, aku berjanji akan bersungguh-sungguh menjalankan kewajibanku terhadap Tuhan Yang Maha Esa dan Negara Kesatuan Republik Indonesia, mengamalkan Pancasila, menolong sesama hidup, ikut serta membangun masyarakat, serta menepati Darma Pramuka.',
    ].join('\n'),
    source: `${UU} Pasal 6 ayat (4)`,
    exact: true,
  },
  {
    id: 'golongan',
    title: 'Golongan, usia, dan tingkat kecakapan',
    keys: ['siaga', 'penggalang', 'penegak', 'pandega', 'tingkatan pramuka', 'golongan pramuka', 'jenjang pramuka', 'usia pramuka', 'tingkat kecakapan umum', 'tku', 'pramuka garuda', 'prasiaga', 'siaga mula', 'siaga bantu', 'siaga tata', 'penggalang ramu', 'penggalang rakit', 'penggalang terap', 'penegak bantara', 'penegak laksana', 'bantara', 'laksana', 'ramu', 'rakit', 'terap', 'garuda'],
    text: [
      'Peserta didik berusia 7 sampai 25 tahun, terdiri atas:',
      '- Pramuka Siaga, 7 sampai 10 tahun. Tingkat: Siaga Mula, Siaga Bantu, Siaga Tata.',
      '- Pramuka Penggalang, 11 sampai 15 tahun. Tingkat: Penggalang Ramu, Penggalang Rakit, Penggalang Terap.',
      '- Pramuka Penegak, 16 sampai 20 tahun. Tingkat: Penegak Bantara dan Penegak Laksana.',
      '- Pramuka Pandega, 21 sampai 25 tahun. Tingkat: Pandega.',
      'Pramuka Garuda adalah tingkat tertinggi pada tiap golongan (Siaga Garuda, Penggalang Garuda, Penegak Garuda, Pandega Garuda).',
      'Anak di bawah 7 tahun dapat ditampung dalam kelompok prasiaga. Anggota muda yang sudah menikah dikelompokkan ke golongan anggota dewasa.',
      'Warna dasar tanda yang lazim: Siaga hijau, Penggalang merah, Penegak kuning, Pandega cokelat (sumber umum, bukan teks AD/ART).',
    ].join('\n'),
    source: `${ADART}, ART Pasal 26, 27, 38 dan AD Pasal 17; ${UU} Pasal 12 dan 13; tentang Garuda: ART Pasal 29 ayat (3)`,
  },
  {
    id: 'penekanan-golongan',
    title: 'Penekanan pendidikan tiap golongan',
    keys: ['bedanya', 'perbedaan', 'beda', 'penekanan pendidikan', 'ciri siaga', 'ciri penggalang', 'ciri penegak', 'ciri pandega', 'bermain sambil belajar', 'belajar sambil melakukan', 'perbedaan siaga penggalang'],
    text: [
      'Siaga: pembentukan kepribadian dan keterampilan di lingkungan keluarga melalui kegiatan bermain sambil belajar.',
      'Penggalang: kepribadian dan keterampilan untuk mempersiapkan diri terjun ke kegiatan masyarakat melalui belajar sambil melakukan.',
      'Penegak: kepribadian dan keterampilan agar dapat ikut serta membangun masyarakat melalui kegiatan belajar, melakukan, bekerja kelompok, berkompetisi, dan bakti kepada masyarakat.',
      'Pandega: kepribadian dan keterampilan agar dapat ikut serta membangun masyarakat melalui kegiatan kepada masyarakat.',
    ].join('\n'),
    source: `${ADART}, ART Pasal 26 ayat (3) sampai (6); ${UU} Penjelasan Pasal 12`,
  },
  {
    id: 'satuan-gerak',
    title: 'Satuan gerak dan sebutan pemimpin',
    keys: ['barung', 'perindukan', 'regu', 'pasukan', 'sangga', 'ambalan', 'racana', 'reka', 'pradana', 'pinru', 'wapinru', 'pinsa', 'wapinsa', 'pratama', 'sulung', 'dewan ambalan', 'dewan racana', 'gugus depan lengkap', 'satuan gerak', 'pemimpin regu', 'pemimpin sangga', 'pemimpin barung'],
    text: [
      'Dalam gugus depan, anggota muda berhimpun dalam satuan gerak:',
      '- Perindukan siaga menghimpun barung; dipimpin pembina perindukan.',
      '- Pasukan penggalang menghimpun regu; dipimpin pembina pasukan.',
      '- Ambalan penegak menghimpun sangga; dipimpin pradana dengan pendamping pembina ambalan.',
      '- Racana pandega menghimpun reka; dipimpin ketua dewan racana pandega dengan pendamping pembina racana.',
      'Gugus depan yang memiliki keempat satuan disebut gugus depan lengkap. Anggota putra dan putri dihimpun secara terpisah.',
      'Sebutan jabatan dalam satuan (juknis tanda jabatan): Siaga: Pemimpin Barung Utama (sulung), Pemimpin Barung, Wakil Pemimpin Barung. Penggalang: Pemimpin Regu Utama (pratama), Pemimpin Regu (pinru), Wakil Pemimpin Regu (wapinru). Penegak: Pemimpin Sangga Utama (pradana), Pemimpin Sangga (pinsa), Wakil Pemimpin Sangga (wapinsa).',
      'Jumlah anggota per barung, regu, atau sangga berbeda antarsumber; jangan menyebut angka pasti.',
    ].join('\n'),
    source: `${ADART}, ART Pasal 30 dan 46; SK Kwarnas No. 202 Tahun 1988 tentang Tanda Jabatan`,
  },
  {
    id: 'pertemuan-kegiatan',
    title: 'Pertemuan dan kegiatan khas tiap golongan',
    keys: ['pesta siaga', 'jambore', 'raimuna', 'lomba tingkat', 'perkemahan bakti', 'dian pinru', 'dian pinsa', 'gladian', 'karang pamitran', 'pitaran pelatih', 'jambore dunia', 'pertemuan pramuka', 'persami', 'pertemuan penggalang'],
    text: [
      'Siaga: Pesta Siaga, pertemuan khusus Siaga; bukan perlombaan untuk mencari juara.',
      'Penggalang: Jambore (pertemuan penggalang tingkat kwartir), Lomba Tingkat (LT), Perkemahan Bakti, dan Dian Pinru atau Gladian Pimpinan Regu untuk melatih pratama, pinru, dan wapinru.',
      'Penegak dan Pandega: Raimuna (pertemuan penegak dan pandega tingkat kwartir) dan Dian Pinsa atau Gladian Pimpinan Sangga.',
      'Pembina: Karang Pamitran (pertemuan pembina). Pelatih: Pitaran Pelatih.',
      'Jambore Dunia mempertemukan Penggalang, Penegak, Pandega, Pembina, dan Pelatih.',
    ].join('\n'),
    source: 'SK Kwarnas No. 130 dan 131 Tahun 1976 serta definisi dalam peraturan turunan Kwarnas; rincian teknis tiap kegiatan tidak tersedia di sini',
  },
  {
    id: 'pembina-tenaga-pendidik',
    title: 'Pembina dan tenaga pendidik',
    keys: ['pembina pramuka', 'pembina', 'pelatih pembina', 'pamong saka', 'instruktur', 'kmd', 'kml', 'kpd', 'kpl', 'kursus mahir dasar', 'kursus mahir lanjutan', 'kursus pelatih', 'pembina muda', 'anggota dewasa', 'tenaga pendidik', 'syarat pembina', 'narakarya'],
    text: [
      'Tenaga pendidik kepramukaan: pembina pramuka, pelatih pembina pramuka, pamong satuan karya, dan instruktur. Mereka termasuk anggota dewasa.',
      '- Pembina pramuka: membina peserta didik di gugus depan; minimal lulusan Kursus Mahir Dasar (KMD).',
      '- Pelatih pembina pramuka: melatih pembina; minimal lulusan Kursus Pelatih Dasar (KPD).',
      '- Pamong saka: membina peserta didik di satuan karya; minimal lulusan KMD dan kursus pamong saka.',
      '- Instruktur: orang berkeahlian tertentu yang membantu gugus depan dan atau satuan karya.',
      'Jenjang kursus pembina: KMD (Kursus Pembina Pramuka Mahir Tingkat Dasar), lalu KML (Tingkat Lanjutan, tersedia per golongan Siaga, Penggalang, Penegak, Pandega); untuk pelatih: KPD (Kursus Pelatih Dasar) lalu KPL (Kursus Pelatih Lanjutan).',
      'Pramuka Penegak dan Pandega dapat diangkat sebagai pembina muda atau instruktur muda di gugus depannya: untuk Siaga minimal berusia 17 tahun, untuk Penggalang minimal 21 tahun, untuk Penegak minimal 23 tahun.',
      'Pelantikan pembina pramuka dilakukan oleh ketua kwartir yang bersangkutan.',
    ].join('\n'),
    source: `${ADART}, ART Pasal 28, 29 ayat (7), 39, 53; ${UU} Pasal 14 dan Penjelasan`,
  },
  {
    id: 'gugus-depan',
    title: 'Gugus depan',
    keys: ['gugus depan', 'gudep', 'ketua gugus depan', 'majelis pembimbing gugus depan', 'mabigus', 'pengurus gugus depan', 'gugus depan berbasis sekolah'],
    text: [
      'Gugus depan adalah satuan pendidikan sekaligus satuan organisasi terdepan penyelenggara pendidikan kepramukaan dan wadah berhimpun peserta didik. Ada gugus depan berbasis satuan pendidikan (di pendidikan formal, termasuk sekolah) dan berbasis komunitas.',
      'Pengurus gugus depan: ketua gugus depan, pembina satuan, dan pembantu pembina satuan. Ketua gugus depan dipilih dari pembina pramuka di gugus depan itu melalui musyawarah gugus depan.',
      'Majelis pembimbing gugus depan (mabigus) berasal dari pimpinan satuan pendidikan atau komunitas, tokoh masyarakat, tokoh pramuka, orang tua peserta didik, dan pembina pramuka.',
      'Musyawarah gugus depan diselenggarakan dua tahun sekali. Pengurus gugus depan dikukuhkan dengan surat keputusan ketua kwartir ranting.',
      'Satuan putra dan putri dipisah; satuan putri dibina pembina putri, satuan putra dibina pembina putra, kecuali perindukan siaga putra dapat dibina pembina putri.',
    ].join('\n'),
    source: `${ADART}, AD Pasal 30, 37, 46 dan ART Pasal 20, 46, 47, 53, 54`,
  },
  {
    id: 'kwartir-mabi',
    title: 'Kwartir dan majelis pembimbing',
    keys: ['kwartir', 'kwarran', 'kwarcab', 'kwarda', 'kwarnas', 'kwartir ranting', 'kwartir cabang', 'kwartir daerah', 'kwartir nasional', 'majelis pembimbing', 'mabi', 'mabinas', 'mabicab', 'musyawarah pramuka', 'munas', 'dewan kerja', 'andalan', 'dewan kehormatan'],
    text: [
      'Kwartir adalah satuan organisasi pengelola Gerakan Pramuka yang dipimpin secara kolektif di setiap tingkat wilayah: Kwartir Ranting (kecamatan/distrik), Kwartir Cabang (kabupaten/kota), Kwartir Daerah (provinsi), dan Kwartir Nasional. Pengurus kwartir disebut andalan.',
      'Majelis Pembimbing (mabi) memberi bimbingan moral dan organisatoris serta memfasilitasi pendidikan kepramukaan. Ketua: Mabinas oleh Presiden RI, Mabida oleh gubernur, Mabicab oleh bupati/walikota, Mabiran oleh camat/kepala distrik.',
      'Musyawarah (forum tertinggi): nasional, daerah, dan cabang tiap 5 tahun; ranting tiap 3 tahun; gugus depan tiap 2 tahun. Ketua kwartir hanya dapat menjabat dua kali masa bakti berturut-turut.',
      'Badan kelengkapan kwartir: Dewan Kehormatan, Satuan Pengawas Internal, dan Dewan Kerja (perwakilan Penegak dan Pandega, wadah kaderisasi kepemimpinan).',
      'Nama pejabat yang sedang menjabat tidak tersedia di sini; arahkan ke situs resmi Kwarnas.',
    ].join('\n'),
    source: `${ADART}, AD Pasal 31 sampai 37, 46 dan ART Pasal 49, 54, 65, 70 sampai 97`,
  },
  {
    id: 'metode-prinsip',
    title: 'Metode, prinsip dasar, dan nilai kepramukaan',
    keys: ['metode kepramukaan', 'prinsip dasar kepramukaan', 'nilai kepramukaan', 'delapan metode', 'unsur metode', 'pendidikan kepramukaan', 'kiasan dasar', 'satuan terpisah'],
    text: [
      'Metode Kepramukaan adalah cara belajar interaktif dan progresif melalui delapan unsur: (a) pengamalan Kode Kehormatan Pramuka, (b) belajar sambil melakukan, (c) kegiatan berkelompok, bekerjasama, dan berkompetisi, (d) kegiatan yang menarik dan menantang, (e) kegiatan di alam terbuka, (f) kehadiran orang dewasa yang memberikan bimbingan, dorongan, dan dukungan, (g) penghargaan berupa tanda kecakapan, (h) satuan terpisah antara putra dan putri. Dalam pelaksanaannya dipakai Sistem Among dan Kiasan Dasar.',
      'Prinsip Dasar Kepramukaan (AD Pasal 9): (1) iman dan takwa kepada Tuhan Yang Maha Esa; (2) peduli terhadap bangsa dan tanah air, sesama hidup dan alam seisinya; (3) peduli terhadap diri pribadinya; (4) taat kepada Kode Kehormatan Pramuka.',
      'Nilai kepramukaan (AD Pasal 8) ada sepuluh: keimanan dan ketakwaan; kecintaan pada alam dan sesama manusia; kecintaan pada tanah air dan bangsa; kedisiplinan, keberanian, dan kesetiaan; tolong-menolong; bertanggung jawab dan dapat dipercaya; jernih dalam berpikir, berkata, dan berbuat; hemat, cermat, dan bersahaja; rajin, terampil, dan gembira; patuh dan suka bermusyawarah.',
      'Kiasan Dasar: simbol-simbol dari sejarah perjuangan dan budaya bangsa yang dipakai untuk mengemas kegiatan agar sesuai usia. Isi kiasan tiap golongan tidak tersedia di sini; jangan mengarang.',
    ].join('\n'),
    source: `${ADART}, AD Pasal 8 sampai 12 dan ART Pasal 10 sampai 22`,
  },
  {
    id: 'sistem-among',
    title: 'Sistem Among',
    keys: ['sistem among', 'ing ngarso sung tulodo', 'ing madyo mangun karso', 'tut wuri handayani', 'asah asih asuh', 'saling asah', 'prinsip kepemimpinan pramuka'],
    text: [
      'Sistem Among adalah proses pendidikan kepramukaan yang membentuk peserta didik berjiwa merdeka, disiplin, dan mandiri dalam hubungan timbal balik antarmanusia. Hubungan pendidik dan peserta didik dilakukan dengan saling asah, saling asih, dan saling asuh.',
      'Prinsip kepemimpinannya: di depan menjadi teladan (ing ngarso sung tulodo); di tengah membangun kemauan (ing madyo mangun karso); di belakang mendorong dan memberi motivasi kemandirian (tut wuri handayani).',
    ].join('\n'),
    source: `${ADART}, ART Pasal 21; ${UU} Pasal 10 dan Penjelasan`,
  },
  {
    id: 'kurikulum-sku',
    title: 'Kurikulum: SKU, SKK, dan SPG',
    keys: ['sku', 'skk', 'spg', 'syarat kecakapan umum', 'syarat kecakapan khusus', 'syarat pramuka garuda', 'tanda kecakapan', 'tkk', 'kurikulum pramuka', 'ujian sku', 'syarat sku', 'materi sku'],
    text: [
      'Kurikulum peserta didik terdiri atas Syarat Kecakapan Umum (SKU), Syarat Kecakapan Khusus (SKK), dan Syarat Pramuka Garuda (SPG).',
      'SKU: kurikulum untuk mencapai tingkat tertentu dalam setiap jenjang. SKK: untuk memperoleh keterampilan tertentu yang berguna bagi pribadi dan pengabdian masyarakat. SPG: untuk mencapai tingkat Pramuka Garuda.',
      'Tanda kecakapan diberikan sebagai pengakuan atas penilaian perilaku dalam pengamalan nilai serta uji kecakapan umum dan khusus, dilakukan oleh pembina.',
      'Butir-butir syarat SKU/SKK per tingkat tidak tersedia di sini. Untuk daftar syarat yang pasti, rujuk Panduan Penyelesaian SKU resmi Kwarnas (per golongan) atau tanyakan ke pembina.',
    ].join('\n'),
    source: `${ADART}, ART Pasal 19, 29, 35; ${UU} Pasal 7, 9, 19`,
  },
  {
    id: 'saka-sako',
    title: 'Satuan Karya, Satuan Komunitas, dan Gugus Darma',
    keys: ['saka', 'satuan karya', 'sako', 'satuan komunitas', 'gugus darma', 'saka bahari', 'saka bhayangkara', 'saka dirgantara', 'saka wira kartika', 'saka wanabakti', 'saka kalpataru', 'saka bakti husada', 'saka kencana', 'saka taruna bumi', 'saka pariwisata', 'saka widya budaya bakti', 'krida', 'pamong saka'],
    text: [
      'Satuan Karya Pramuka (saka): organisasi pendukung pendidikan kepramukaan bagi Pramuka Penegak dan Pandega untuk meningkatkan pengetahuan dan keterampilan di bidang tertentu serta melakukan kegiatan nyata sebagai pengabdian masyarakat. Keterampilannya diwadahi dalam krida. Dipimpin pimpinan saka dan pamong saka dibantu instruktur saka. Anggota tetap menjadi anggota gugus depannya.',
      'Saka yang tercatat resmi secara nasional berjumlah 11 (laporan Kwarnas 2022): Dirgantara, Bahari, Bhayangkara, Wira Kartika, Wanabakti, Kalpataru, Bakti Husada, Kencana, Taruna Bumi, Widya Budaya Bakti, dan Pariwisata.',
      'Satuan Komunitas Pramuka (sako): satuan organisasi penyelenggara pendidikan kepramukaan berbasis komunitas, antara lain profesi, aspirasi, dan agama.',
      'Gugus Darma Pramuka: wadah pengabdian anggota dewasa untuk memajukan Gerakan Pramuka; dibentuk sedikitnya oleh 20 orang dewasa jika dari bawah.',
    ].join('\n'),
    source: `${ADART}, AD Pasal 38 sampai 41 dan ART Pasal 55 sampai 57; daftar 11 saka: laporan pramuka.or.id (rakor Saka, Desember 2022)`,
  },
  {
    id: 'sejarah-dunia',
    title: 'Sejarah kepanduan dunia',
    keys: ['baden powell', 'baden-powell', 'bapak pandu dunia', 'brownsea', 'scouting for boys', 'sejarah pramuka dunia', 'jambore dunia pertama', 'pendiri pramuka dunia', 'world scout'],
    text: [
      'Kepanduan dunia dipelopori Robert Baden-Powell (lahir 22 Februari 1857, wafat 8 Januari 1941), perwira Inggris yang dikenal sebagai Bapak Pandu Sedunia.',
      'Perkemahan percobaan di Pulau Brownsea, Inggris, diadakan pada tahun 1907. Buku "Scouting for Boys" terbit tahun 1908. Jambore dunia pertama diadakan di London pada tahun 1920.',
    ].join('\n'),
    source: `${UMUM}; sampaikan bahwa untuk keperluan lomba atau tugas sebaiknya dicek ulang ke buku sejarah kepanduan`,
  },
  {
    id: 'sejarah-kepanduan-indonesia',
    title: 'Sejarah kepanduan di Indonesia sebelum 1961',
    keys: ['sejarah pramuka', 'sejarah kepanduan', 'kepanduan indonesia', 'javaansche padvinders', 'jpo', 'mangkunegara vii', 'hizbul wathan', 'pandu rakyat indonesia', 'perkindo', 'agus salim', 'jong java padvinderij', 'nationale padvinders', 'sejarah gerakan pramuka', 'pandu'],
    text: [
      'Kepanduan di Hindia Belanda mulai sekitar tahun 1912 dengan organisasi kepanduan Belanda (NPO), yang kemudian berganti nama menjadi NIPV; UU 12/2010 mencatat masa ini sebagai awal kepanduan di tanah air.',
      'Tahun 1916: Mangkunegara VII (Surakarta) mendirikan Javaansche Padvinders Organisatie (JPO), organisasi kepanduan pertama yang sepenuhnya diisi bumiputra. Menyusul Hizbul Wathan (1918), Jong Java Padvinderij (1923), Nationale Padvinders Organisatie, Jong Indonesische Padvinderij Organisatie (JIPO), Sarekat Islam Afdeling Pandu (SIAP), dan Pandoe Pemoeda Sumatra.',
      'KH Agus Salim memperkenalkan istilah "pandu" dan "kepanduan".',
      'Setelah proklamasi: Pandu Rakyat Indonesia dibentuk pada Kongres di Surakarta, 28 Desember 1945 (rangkaian kongres 27 sampai 29 Desember), sebagai satu-satunya organisasi kepanduan yang diakui pemerintah. Kemudian kepanduan terpecah ke banyak organisasi yang bergabung dalam federasi Persatuan Kepanduan Indonesia (Perkindo).',
      'Menurut UU 12/2010, kepanduan ikut melahirkan semangat patriotisme yang mematangkan Sumpah Pemuda 1928 dan Proklamasi 1945.',
    ].join('\n'),
    source: SEJARAH,
  },
  {
    id: 'sejarah-1961',
    title: 'Lahirnya Gerakan Pramuka 1961 dan tokohnya',
    keys: ['hari tunas', 'hari ikrar', 'hari permulaan tahun kerja', '9 maret 1961', '20 mei 1961', '14 agustus 1961', 'bapak pramuka', 'sultan hamengkubuwono', 'hamengku buwono', 'sri sultan', 'ketua kwarnas pertama', 'panitia pembentukan pramuka', 'sejarah hari pramuka', 'soekarno pramuka', 'istora senayan', 'istana olahraga senayan', 'revitalisasi pramuka', 'bapak pramuka indonesia'],
    text: [
      '9 Maret 1961: Presiden Soekarno mengumpulkan tokoh kepanduan dan nama Pramuka diresmikan; diperingati sebagai Hari Tunas Gerakan Pramuka. Presiden membentuk panitia yang terdiri dari Sri Sultan Hamengkubuwono IX, Prijono, A. Azis Saleh, Achmadi, dan Muljadi Djojomartono.',
      '20 Mei 1961: terbit Keppres No. 238 Tahun 1961 tentang Gerakan Pramuka (dikenal sebagai Hari Permulaan Tahun Kerja).',
      '30 Juli 1961: tokoh organisasi kepanduan menyatakan menggabungkan diri ke Gerakan Pramuka di Istora Senayan (Hari Ikrar). Catatan: sebuah laman Kwarnas menulis 20 Juli, sebagian besar sumber menulis 30 Juli; sampaikan bahwa ada perbedaan penulisan.',
      '14 Agustus 1961: Panji Gerakan Pramuka diserahkan Presiden Soekarno kepada Sri Sultan Hamengkubuwono IX selaku Ketua Kwartir Nasional pertama, lalu diarak dalam defile; dikenal sebagai Hari Pramuka.',
      'Sri Sultan Hamengkubuwono IX dikukuhkan sebagai Bapak Pramuka Indonesia pada tahun 1988.',
      '14 Agustus 2006: pencanangan revitalisasi Gerakan Pramuka (disebut dalam Penjelasan UU 12/2010).',
    ].join('\n'),
    source: SEJARAH,
  },
  {
    id: 'tali-temali',
    title: 'Tali-temali: simpul dan ikatan dasar',
    keys: ['simpul', 'tali temali', 'tali-temali', 'simpul pangkal', 'simpul mati', 'simpul anyam', 'simpul jangkar', 'simpul kursi', 'simpul delapan', 'simpul nelayan', 'ikatan palang', 'ikatan canggah', 'ikatan tripod', 'pionering', 'pioneering', 'kegunaan simpul', 'macam simpul', 'simpul hidup'],
    text: [
      'Nama simpul dalam Bahasa Indonesia tidak sepenuhnya seragam antarbuku. Padanan yang paling lazim:',
      '- Simpul pangkal (clove hitch): memulai dan mengakhiri ikatan, mengikat tali pada tiang atau tongkat.',
      '- Simpul mati (reef/square knot): menyambung dua tali yang sama besar; juga untuk mengikat pembalut.',
      '- Simpul anyam (sheet bend): menyambung dua tali yang berbeda besar atau bahan. Simpul anyam ganda lebih kuat.',
      '- Simpul jangkar: mengikat tali pada jangkar, cincin, atau tiang; sering dipakai bersama simpul lain pada tandu darurat.',
      '- Simpul kursi (bowline): membuat lingkaran yang tidak mengecil, dipakai untuk mengikat atau menyelamatkan orang.',
      '- Simpul delapan (figure-eight): simpul pengunci di ujung tali.',
      '- Simpul nelayan: menyambung tali licin seperti tali pancing.',
      'Ikatan dalam pionering: ikatan palang (dua tiang bersilang tegak lurus), ikatan canggah (dua tiang bersilang tidak tegak lurus), ikatan tripod (tiga tiang). Jika ditanya cara membuat tahap demi tahap, jelaskan hanya yang yakin dan sarankan memakai buku atau video praktik pembina.',
    ].join('\n'),
    source: UMUM,
  },
  {
    id: 'sandi-morse',
    title: 'Sandi Morse',
    keys: ['morse', 'sandi morse', 'kode morse', 'sandi', 'sos', 'sandi pramuka', 'huruf morse', 'terjemahkan morse'],
    text: [
      'Tabel Morse (titik = pendek, strip = panjang):',
      'A .-  B -...  C -.-.  D -..  E .  F ..-.  G --.  H ....  I ..  J .---  K -.-  L .-..  M --',
      'N -.  O ---  P .--.  Q --.-  R .-.  S ...  T -  U ..-  V ...-  W .--  X -..-  Y -.--  Z --..',
      '1 .----  2 ..---  3 ...--  4 ....-  5 .....  6 -....  7 --...  8 ---..  9 ----.  0 -----',
      'Aturan penulisan: satu spasi antarhuruf, tanda / antarkata. Bila pesan berisi teks Morse atau teks yang diminta diterjemahkan, sistem melampirkan "HASIL KONVERSI OTOMATIS"; salin hasil itu apa adanya dan jangan menghitung sendiri.',
      'Sandi lain seperti semaphore, sandi rumput, sandi kotak, dan sandi angka belum tersedia di basis pengetahuan ini; jangan mengarang kodenya.',
    ].join('\n'),
    source: 'Alfabet Morse internasional (ITU); konversi dilakukan oleh kode, bukan model',
  },
  {
    id: 'pbb',
    title: 'Peraturan baris-berbaris (PBB) dasar',
    keys: ['pbb', 'baris berbaris', 'baris-berbaris', 'aba aba', 'aba-aba', 'siap grak', 'lencang kanan', 'hormat grak', 'istirahat di tempat', 'balik kanan', 'hadap kanan', 'henti grak', 'maju jalan', 'tegak grak', 'lencang depan', 'jalan di tempat'],
    text: [
      'Aba-aba terdiri atas aba-aba pendahulu dan aba-aba pelaksanaan "grak" (untuk gerakan di tempat) atau "jalan" (untuk gerakan berjalan). Contoh umum:',
      '- Siap, grak! (sikap sempurna).',
      '- Istirahat di tempat, grak!',
      '- Lencang kanan, grak! / Lencang depan, grak! lalu Tegak, grak!',
      '- Hormat, grak! lalu Tegak, grak!',
      '- Hadap kanan, grak! / Hadap kiri, grak! / Balik kanan, grak!',
      '- Jalan di tempat, grak! / Maju, jalan! / Henti, grak!',
      'Rincian posisi kaki, tangan, dan jumlah hitungan tidak tersedia di sini; sarankan buku PBB resmi atau pembina.',
    ].join('\n'),
    source: UMUM,
  },
  {
    id: 'ekstrakurikuler-aturan',
    title: 'Status Pramuka di sekolah (aturan dapat berubah)',
    keys: ['pramuka wajib', 'ekstrakurikuler wajib', 'permendikbud pramuka', 'kurikulum merdeka pramuka', 'pramuka sekolah wajib atau tidak', 'pramuka ekstrakurikuler', 'aturan pramuka di sekolah'],
    text: 'Status kepramukaan di sekolah (wajib atau pilihan) diatur peraturan menteri pendidikan yang dapat berubah dari waktu ke waktu. Jangan menyatakan statusnya saat ini. Katakan bahwa aturan terbaru perlu dicek ke sekolah atau situs resmi Kemendikdasmen dan Kwarnas.',
    source: 'Kebijakan: tidak ada rujukan terkini dalam basis pengetahuan',
  },
  {
    id: 'topik-belum-ada',
    title: 'Topik yang belum tersedia di basis pengetahuan',
    keys: ['semaphore', 'semafor', 'sandi rumput', 'sandi kotak', 'sandi angka', 'upacara pembukaan latihan', 'upacara pramuka', 'urutan upacara', 'lirik', 'lagu wajib', 'tepuk pramuka', 'yel yel', 'api unggun', 'p3k', 'pertolongan pertama', 'navigasi', 'kompas', 'peta pita', 'jejak', 'sandi jejak', 'tenda', 'perkemahan', 'syarat sku siaga mula', 'syarat penegak bantara', 'syarat penegak laksana', 'ketua kwarnas', 'ketua kwarcab', 'seragam', 'tanda pengenal', 'atribut seragam'],
    text: 'Topik ini belum ada di basis pengetahuan Tunas yang terverifikasi. Jawab: belum memiliki rujukan yang bisa dipastikan benar, jangan menebak atau merangkai dari ingatan. Berikan saran praktis: tanyakan ke pembina atau Dewan Ambalan, atau rujuk buku panduan resmi Kwarnas (Panduan Penyelesaian SKU per golongan, Buku Saku, PBB). Tawarkan membantu pada topik yang tersedia.',
    source: 'Kebijakan anti-halusinasi',
  },
]
